from typing import Protocol

from gestor_inventory.domain.rbac import Permission, Role


class RoleRepository(Protocol):
    def get_role(self, *, company_id: int, role_id: int) -> Role | None: ...

    def list_roles(self, *, company_id: int) -> list[Role]: ...


class PermissionRepository(Protocol):
    def get_permission_by_code(self, *, code: str) -> Permission | None: ...

    def list_permissions(self) -> list[Permission]: ...


class UserRoleRepository(Protocol):
    def user_belongs_to_company(self, *, company_id: int, user_id: int) -> bool: ...

    def role_belongs_to_company(self, *, company_id: int, role_id: int) -> bool: ...

    def assign_role_to_user(self, *, company_id: int, user_id: int, role_id: int) -> bool: ...

    def revoke_role_from_user(self, *, company_id: int, user_id: int, role_id: int) -> bool: ...


class UserAccessRepository(Protocol):
    def list_user_role_names(self, *, company_id: int, user_id: int) -> list[str]: ...

    def list_user_permission_codes(self, *, company_id: int, user_id: int) -> list[str]: ...
